name: Salesforce Delta Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Salesforce CLI (via npm)
        run: |
          npm install -g @salesforce/cli
          sf update

      - name: Install Delta plugin (stable version)
        run: sf plugins install sfdx-git-delta@5.4.1

      - name: Authenticate with JWT
        env:
          SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
        run: |
          echo "$SFDX_JWT_KEY" > server.key
          sf org login jwt \
            --client-id "$SFDX_CLIENT_ID" \
            --jwt-key-file server.key \
            --username "$SF_USERNAME" \
            --alias target-org \
            --set-default
          rm server.key

      - name: Generate delta package
        run: |
          PREVIOUS_SHA=${{ github.event.before }}
          if [ -z "$PREVIOUS_SHA" ]; then
            PREVIOUS_SHA=$(git rev-parse HEAD~1)
          fi

          mkdir delta-out

          sf delta package \
            --from "$PREVIOUS_SHA" \
            --to ${{ github.sha }} \
            --output delta-out

      - name: Deploy delta metadata
        run: |
          sf project deploy start \
            --source-dir delta-out \
            --target-org target-org \
            --test-level RunLocalTests \
            --wait 30
