name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate with JWT
        env:
          SFDX_JWT_KEY: ${{ secrets.SFDX_JWT_KEY }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
        run: |
          echo "$SFDX_JWT_KEY" > server.key
          sf org login jwt \
            --client-id "$SFDX_CLIENT_ID" \
            --jwt-key-file server.key \
            --username "$SF_USERNAME" \
            --alias target-org \
            --set-default
          rm server.key

      - name: Detect changed metadata
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^force-app/" || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Deploy only changed metadata
        if: env.CHANGED_FILES != ''
        run: |
          mkdir changed-md
          for file in $CHANGED_FILES; do
            mkdir -p changed-md/$(dirname $file)
            cp $file changed-md/$file
          done

          sf project deploy start \
            --source-dir changed-md \
            --target-org target-org \
            --test-level RunLocalTests \
            --wait 30
